baseURL = "https://isidro-fco.github.io/Paradigmas_Prog/"
languageCode = "es-es"
title = "Paradigmas de Programación"
theme = "ananke"

relativeURLs = false
canonifyURLs = true

[publishDir]
  directory = "public"

[params]
  description = "Sitio para la materia de Paradigmas de Programación"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "paradigmas_progm"
    name = "Paradigmas de la Programación"
    title = "paradigmas_progm"
    url = "/paradigmas_progm/"
    weight = 0